version: "3.7"

services:
  backend:
    volumes:
      - ~/.m2:/root/.m2
    build:
      context: .
    expose:
      - 8080
    command: java -jar backend.jar
  ui:
    volumes:
      - ~/.m2:/root/.m2
    build:
      context: .
    depends_on:
      - backend
    ports:
      - "80:80"
    command: ['java',
              '-Dbackend.graphql-url=http://backend:8080/graphql',
              '-Dbackend.web-socket-url=ws://backend:8080/subscriptions',
              '-jar', 'ui.jar']
